CREATE TABLE `users` (
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`fullname` VARCHAR(255) NOT NULL,
	`secretCode` VARCHAR(10) NOT NULL UNIQUE,
	`pin` VARCHAR(6) NOT NULL,
	`balance` DOUBLE NOT NULL DEFAULT 0,
	PRIMARY KEY(`username`)
);

CREATE TABLE `transactionHistories` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(50) NOT NULL,
	`type` VARCHAR(8) NOT NULL,
	`from` VARCHAR(50) NOT NULL,
	`amount` DOUBLE NOT NULL,
	`time` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);

ALTER TABLE `transactionHistories`
ADD FOREIGN KEY(`username`) REFERENCES `users`(`username`)
ON UPDATE CASCADE ON DELETE CASCADE;